### ISSUE TITLE
Add a way to list commands

### ISSUE THREAD

**Issue by Zykino** [Kruiser8/Kruiz-Control#11]
Bot often have a `!help` or `!commands` command that can list all the commands it knows.
I know KC is more than a command bot but it can be nice to be able to create this sort of command on KC. I am expecting a configuration on the line of:
```
OnCommand a 0 !example
Chat Send _CommandList_
```

Not sure of the syntax but I wanted to show that I do not want KC to hardcode the command, just give the possibility to have it or not on a stream.

Note: I wanted to implement it myself to get into the code... but I did not have a lot of time recently. And I am not sure how to enter the project code wise.
I have the feeling that the _CommandList_ variable will be generated by the `this.commandsInfo` (or not info one ? not sure) from https://github.com/Kruiser8/Kruiz-Control/blob/master/js/chat/chatHandler.js
But I am not sure if `Chat Send` refers to the line 147 of the same file (where there is an `if/else` `send/whisper`.

**Comment by Kruiser8** [comment]
It's definitely something that could work. The controller.js could call a getAllCommands method on the chat handler and use that to produce a string output.

It's not OOTB, but you could add each command to a List and send an export of the list to chat. That would definitely allow the most control if you wanted some commands to be skipped in the list.

Thanks for the suggestion!

**Comment by Kruiser8** [comment]
I added this to the trello board, so will close it here.
