### ISSUE TITLE
OBS Volume doc

### ISSUE THREAD

**Issue by Zykino** [Kruiser8/Kruiz-Control#12]
In the Documentation, this sentence is... not complete:
> Note, volume stands for the is not a percentage.
Maybe change it to something like the following:
> Note: the volume stands for a value that does not look like a percentage to the human hear.

For your information and a better phrasing, apparently OBS is made with Qt, and the Qt doc around volume is explained here: https://doc.qt.io/qt-5/qml-qtmultimedia-video.html#volume-prop. I did not check OBS code to confirm but apparently the volume you have is a percentage, but the human hear works logarithmically, not in a percentage manner.

**Comment by Kruiser8** [comment]
Oops. Thanks for catching that. 

I know the OBS websocket also has some language that describes what the percentage means, so I'll cross reference both. 

The latest websocket came with db control rather than percentage control so may switch to that as well.

**Comment by Kruiser8** [comment]
This is resolved in the latest version.
