### ISSUE TITLE
OnSETwitchBulkGiftSub not triggering

### ISSUE THREAD

**Issue by JoelDickinson** [Kruiser8/Kruiz-Control#15]
OnSETwitchBulkGiftSub doesn't seem to trigger anything. I've attempted the below trigger with no success.

OnSETwitchBulkGiftSub
Chat Send "Gift sub"

I've got OnSETwitchGiftSub and others working so hopefully that can rule out user error :)

**Comment by Kruiser8** [comment]
Hey, Joel. When testing, we did find that your gifted subs were coming in individually through your alert box. KC follows what SE says is happening, so if you get multiple alerts for a bulk gift sub, then KC will fire an OnSETwitchSub for each sub.

I would try to figure out why SE is firing individual sub alerts for a bulk gifted sub event. That should solve the problem.

**Comment by Kruiser8** [comment]
Hey Joel,

Closing this issue until we are able to determine why SE isn't giving you bulk sub alerts. KC only follows what SE says is happening, so if you're getting 5 alerts for a bulk gifted sub, then that's an issue with how SE is configured or handling the alerts. At that point, there's nothing else KC can do.

-Kruiser
