### ISSUE TITLE
ulencode # in api call

### ISSUE THREAD

**Issue by metabubble** [Kruiser8/Kruiz-Control#18]
Problem:

I am trying to pass chat text via API GET. I noticed that when texts contain #, they are cut off, because of # works obviously.

Possible solutions:

Is there a way to replace # by %23 so it gets passed as the query string? Since we are talking about an API call, having a local part of the URL makes no sense anyways.

Alternatively, having API POST could work around the issue as well.

**Comment by Kruiser8** [comment]
Use [`Function`](https://github.com/Kruiser8/Kruiz-Control/blob/master/js/Documentation.md#function).

```
OnCommand s 0 !test
Function "return { encoded: encodeURIComponent([message]) };"
API GET "http://my.api.com/param={encoded}"
```

**Comment by metabubble** [comment]
That works like a charm! Thank you!
