### ISSUE TITLE
StreamLabs, Refreshing Casche makes Bot Unresponsive.

### ISSUE THREAD

**Issue by dejavudea** [Kruiser8/Kruiz-Control#22]
I redid the process from scratch to find what made the bot unresponsive was when I hit the "Refresh cache of current page" button on the Browser source. The tutorial advises to do so when you make changes and save on your trigger doc. 

The bot was working and responding up until this point using !example. 

Please advise, thank you!

**Comment by Kruiser8** [comment]
You have a syntax error in one of your trigger files. Common issues are:

- Missing the cooldown argument on the `OnCommand` trigger.
- Lines that cannot be parsed due to unquoted inputs or un-escaped `'` and `"` values.

For more direct help, [join the discord](https://discord.gg/wU3ZK3Q).

**Comment by dejavudea** [comment]
I'm copying the example text used in the tutorial line per line. I do not think that is the issue.

**Comment by Kruiser8** [comment]
The tutorial video on youtube is a little old. Please add a cooldown to your `OnCommand` lines like so: `OnCommand b 0 !myCommand`.
