### ISSUE TITLE
[feature request] Add support for choosing what channel(s) the chat messages are sent to

### ISSUE THREAD

**Issue by japalo** [Kruiser8/Kruiz-Control#23]
I today started tweaking a bit with the chatHandler to allow for my bot account to send messages to my streaming account.
What i ended up doing was to add a third txt-file into the settings folder called "channel.txt" and read it in the chatHandlerExport, and passed the value when initializing:

```
async function chatHandlerExport() {
  var chat = new ChatHandler();
  var user = await readFile('settings/chat/user.txt');
  var oauth = await readFile('settings/chat/oauth.txt');
  var channel = await readFile('settings/chat/channel.txt'); // Can be empty? Also, comma separated channels here?
  chat.init(user.trim(), oauth.trim(), channel.trim());
}
```
And then in the initialization:

```
init(user, oauth, channel) {
  this.channel = user.toLowerCase();
  ComfyJS.onConnected = ( address, port, isFirstConnect ) => {
    if (isFirstConnect) {
      this.success();
    }
  }
  if (user) {
    if (oauth) {
      // Needs proper null/undefined/falsy check for channel here
      ComfyJS.Init(user, oauth, channel);
    } else {
      ComfyJS.Init(user);
    }
  }
}
```
This of course works fine and dandy for myself, but for the other people out there, maybe they want the option to do this as well. I suggest adding something like this, with comma-separation in "channel.txt" for multiple channels if wanted, and some null/undefined/falsy checks in the initialization.

Found the solution to connect to another channel via https://github.com/instafluff/ComfyJS#joining-a-different-channel.

If this feature request is denied, maybe this could help others out there.

The check for falsy could of course be replaced with something like `ComfyJS.Init(user, oauth, (channel || user));` if you wanna do something quick and dirty however. Not sure what i think about that solution though.

Cheers, and thank you for awesome software!

**Comment by Kruiser8** [comment]
I'm a little confused as to the use case and why the modification was needed. The `user.txt` is used to determine which channel is connected to. The `oauth.txt` determines which user is sending the messages. So, if you wanted your bot to send messages to your streamer's channel, you would:

- put the streamer name into `user.txt`,
- generate the oauth token using the bot, and
- put that token into `oauth.txt`.

After that, your bot would be sending messages to the streamer's channel without any modification.

**Comment by japalo** [comment]
Aha! I thought the `user.txt` was there for user name for a login, and the oath token was a replacement for password. Then this makes a lot more sense.  Then the use case for this feature request would be if you want your message to be sent to multiple channels at once i guess, since ComfyJS supports that. Not sure when this would be needed, maybe in squad streams or similar but that's just grasping for straws at this point.

I guess we can disregard this post then. Thanks for quick reply!
