### ISSUE TITLE
Documentation - API Send Example says API Method instead

### ISSUE THREAD

**Issue by Gambloide** [Kruiser8/Kruiz-Control#32]
Just wanted to mention the `API Send` documentation says `API Method` in the given example instead of `API Send`

https://github.com/Kruiser8/Kruiz-Control/blob/master/js/Documentation.md#api-send

**Comment by Kruiser8** [comment]
Thanks for catching that and reporting! I'll get that updated shortly.

**Comment by Kruiser8** [comment]
Fixed in this commit: https://github.com/Kruiser8/Kruiz-Control/commit/62dea42601833e3eaf5afdeeac858cae7e66e30f
