### ISSUE TITLE
Permission Check for u-Flag is not Case Insensitive

### ISSUE THREAD

**Issue by Gambloide** [Kruiser8/Kruiz-Control#34]
The documentation for [Chat Triggers](https://github.com/Kruiser8/Kruiz-Control/blob/master/js/Documentation.md#chat-triggers) states the username for the `u` flag is case insensitive.

However, with v1.5.1 at least, any username given with uppercase characters does not cause the trigger to fire.

``` bash
# This works
OnCommand u gambloide 0 "!testa"
Log "Test A works"

#This does not work
OnCommand u Gambloide 0 "!testb"
Log "Test B works"
```

The cause is in `checkPermissions` in `chatHandler.js`. While the `user` parameter is transformed to lower case, the `info` parameter given in the trigger is not transformed to lower case.

``` javascript
/**
   * Register trigger from user input.
   * @param {string} user twich username that sent message
   * @param {object} flags permission flags for the user
   * @param {string} permissions usability of the command or keyword
   * @param {string} info extra information for the usability
   */
  checkPermissions(user, flags, permissions, info) {
    user = user.toLowerCase();
    if (
      (permissions.includes('e')) ||
      (permissions.includes('s') && flags.subscriber) ||
      (permissions.includes('v') && flags.vip) ||
      (permissions.includes('f') && flags.founder) ||
      (permissions.includes('m') && flags.mod) ||
      (permissions.includes('b') && this.channel === user) ||
      (permissions.includes('n') && !flags.founder && !flags.subscriber && !flags.vip && !flags.mod && this.channel !== user) ||
      (permissions.includes('u') && info && user === info)
    ){
      return true;
    }
    return false;
  }
```
  
Adding `info = info.toLowerCase();` before the permissions check fixes the issue.

**Comment by Kruiser8** [comment]
Thanks for reporting! This is fixed on the develop branch and will be released shortly.

**Comment by Gambloide** [comment]
Just a heads-up. I realized this breaks any command without `info` provided.
I just added a quick check around the transform so it doesn't crash.

``` javascript
if (info) {
  info = info.toLowerCase();
}
```

**Comment by Kruiser8** [comment]
Fixed in develop: https://github.com/Kruiser8/Kruiz-Control/commit/f139c7b46bdb55676720126971a0950ced1b3fa1
