### ISSUE TITLE
How to use Conditionals

### ISSUE THREAD

**Issue by F0x1fy** [Kruiser8/Kruiz-Control#37]
How does one properly use an "If" statement? I had tried a few different ways to do this, but to no avail. The documentation doesn't help much either. I tried it both like this:
```
OnChannelPoint e "Retro Mode"
If {OBS CurrentScene} = "Main"
Play 100 nowait "Retro Mode.wav"
OBS Scene CRT
Delay 60
OBS Scene Main
```
And like this:
```
OnChannelPoint e "Retro Mode"
If OBS CurrentScene = "Main"
Play 100 nowait "Retro Mode.wav"
OBS Scene CRT
Delay 60
OBS Scene Main
```
Yet it seems to still not trigger, despite being in the "Main" scene. What exactly am I doing wrong here?

**Comment by Kruiser8** [comment]
Hey F0x1fy,

You're very close to the right answer here. Except for `Random` logic, you cannot use multiple actions on a line. You have to use the values returned by an action ([parameters](https://github.com/Kruiser8/Kruiz-Control/blob/master/js/Documentation.md#parameters)).

[`OBS CurrentScene`](https://github.com/Kruiser8/Kruiz-Control/blob/master/js/Documentation.md#obs-currentscene) returns the `current_scene` parameter that you can leverage on future lines. So, the code would look like
```
OnChannelPoint e "Retro Mode"
OBS CurrentScene
If {current_scene} = "Main"
Play 100 nowait "Retro Mode.wav"
OBS Scene CRT
Delay 60
OBS Scene Main
```

**Comment by Kruiser8** [comment]
Also, side note, the [`OnChannelPoint`](https://github.com/Kruiser8/Kruiz-Control/blob/master/js/Documentation.md#onchannelpoint) trigger does not take a permission action, so the `e` means nothing in this case.

**Comment by F0x1fy** [comment]
Wow, thank you for the swift response! Just in time for my stream haha. I cut this one a bit close :P Greatly appreciated!!! I may even consider contributing to this project if you're open to PRs. Anyways, this was a lot of help! Thank you, and I hope you have a great day/night!
