### ISSUE TITLE
OnSLOBSSwitchScenes is not triggered

### ISSUE THREAD

**Issue by darkphan** [Kruiser8/Kruiz-Control#4]
The OnSLOBSSwitchScenes trigger does not appear to work. I did a little digging and it seems changing line 35 of slobsHandler.js from: 

`          this.onSwitchTrigger[scene] = triggerId;` 

to 

`          this.onSwitchTrigger[scene].push(triggerId);` 

appears to fix things.

**Comment by Kruiser8** [comment]
Hi @darkphan, thanks for the ticket!  This has been fixed.
