### ISSUE TITLE
ResponsiveVoice not working properly

### ISSUE THREAD

**Issue by BMF54123** [Kruiser8/Kruiz-Control#40]
ResponsiveVoice does not seem to work properly unless you manually add the script tag to Kruiz-Control's **index.html**. I followed the instructions for setting it up to the letter (create account, add script tag to **settings/tts/tag.txt**, add TTS action to **triggers.txt**) and could not get it to do anything, not even play a preset welcome message, which implies that the script was not running at all. I'm running OBS 27.2.3; is it possible that the recent CEF update broke something? I hadn't tried using TTS actions until tonight, so I can't verify whether it worked in previous versions or not.

**Comment by Kruiser8** [comment]
Hi @BMF54123, thanks for reporting. This was reported yesterday and I just finished an update which switches Kruiz Control to use the default narration / text-to-speech on your computer. This will be released in the next version.

**Comment by Kruiser8** [comment]
Responsive voice has been removed in 1.5.5 and TTS now uses the default narration on your computer.
