### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by bonny1992** [Kruiser8/Kruiz-Control#41]
Heya!

First of all, this seems to be really cool.

Second, can Kruiz Control play some videos or show some images when an user uses bits, for example?

Thank you!

**Comment by Kruiser8** [comment]
Most people achieve that by having KC toggle video/image/other media in OBS or Streamlabs Desktop.

Other folks have custom edited KC to show videos/images via the index.html.

**Comment by bonny1992** [comment]
> 

Many thanks for your reply!

I'd be very much inclined to the second option, could you give me some pointers to do it myself, or point me to some people you know have this kind of customization?
Thank you very much and I'll try KC in the next days for sure!

**Comment by Kruiser8** [comment]
In the Kruiz Control discord, Bilago posted a few messages related to adding a video action:
https://discord.com/channels/687441986491514970/687663165433184432/854554023389298690

**Comment by bonny1992** [comment]
> In the Kruiz Control discord, Bilago posted a few messages related to adding a video action: https://discord.com/channels/687441986491514970/687663165433184432/854554023389298690

Oh, I did not expect a reply this fast :D

Thank you, I will surely check the messages as soon as I can!

**Comment by TheTaraStark** [comment]
What's the likelihood the solution Bilago suggested could be implemented into vanilla release?
