### ISSUE TITLE
Obs Source not working

### ISSUE THREAD

**Issue by Tezzerbear** [Kruiser8/Kruiz-Control#42]
I have a source set up where a channel point redeem can be bought to give my avatar headpats. It has worked perfectly up until the last 2 days, where the set source isn't triggering on. 
I haven't changed anything amongst the code, and nothing in my streams has changed, the headpats just no longer trigger and I'm not sure why.

This is what I have set up (I've cut out the chat sends because there are a lot)
OnChannelPoint "Headpats!"
OBS Source headpats on
Random Equal "Chat Send
Delay 5
OBS Source headpats off

Any help would be amazing to help me get this back up and running!

**Comment by Kruiser8** [comment]
Closing this issue since it's been a week with no updates.
