### ISSUE TITLE
tts folder doesnt exist

### ISSUE THREAD

**Issue by jeovanny315** [Kruiser8/Kruiz-Control#43]
im going through changing the settings files and there isnt a tts folder or responsive voice script. how would i fix that?

**Comment by Kruiser8** [comment]
As of 1.5.5, there is no longer a TTS settings folder or responsive voice script.

I forgot to update the settings page, and I will do that shortly.

**Comment by Kruiser8** [comment]
Settings instruction updated and removed the TTS section. TTS now uses the narration component of your computer. No setting needed.
