### ISSUE TITLE
OnChannelPoint triggers sources on other scenes similar to OnCommand and OnSpeak (I don't know how to label things as enhancement) 

### ISSUE THREAD

**Issue by REALtony4twenty** [Kruiser8/Kruiz-Control#44]
I use the "[downstream keyer](https://obsproject.com/forum/resources/downstream-keyer.1254/)" plugin by Exeldro. 
Combining this plugins features with the downstream keyer would keep things organized. Allowing alerts that you want to show at all times to be on a single scene but still show when you switch scenes during stream so you dont need to remake the same source over and over or copy it with "source copy" also by Exeldro. 

I want to make sure no matter what Im doing all channel point redemptions will show and this functionality would solve that issue :)

**Comment by Kruiser8** [comment]
I'm unclear what's being requested.

How is this different from putting everything you want triggered into a scene and nesting that scene where you want to use it?

I'm also not understanding the difference being highlighted between OnChannelPoint and OnCommand.

If you use OBS SceneSource, then the sources don't have to be on the given scene to update, but I'm unsure that's what you want.

**Comment by REALtony4twenty** [comment]
How can I make OBS SceneSource work when someone use Channel Points on twitch? If I can do that then Im fine and we can ignore everything else

**Comment by Kruiser8** [comment]
You can use any trigger with any action, so just put them in the same event. An example:
```m
OnChannelPoint "Head Pat"
OBS SceneSource "Webcam" "Head Pat" on
Delay 5
OBS SceneSource "Webcam" "Head Pat" off
```

**Comment by REALtony4twenty** [comment]
Ill try this method again

**Comment by REALtony4twenty** [comment]
so Im trying to get this to work with "media"

**Comment by Kruiser8** [comment]
Media in OBS would be considered a source that you could turn on and off. Otherwise, You could use the OBS Media actions.

For more direct support, please [join the discord](https://discord.gg/wU3ZK3Q).
