### ISSUE TITLE
User name is not recognized in OnCommand when Non-Alphabet characters is used as DisplayName.

### ISSUE THREAD

**Issue by formulynx** [Kruiser8/Kruiz-Control#47]
Hi @Kruiser8, thank you for developing great plugin!
I'm using KC for about 3 months, and recently tried to add Chat Trigger command for me and my mods.

`OnCommand bm 10 !example`

but it didn't work, although my other commands are working e.g. OnInit/OnChannelPoint/OnSETwitchRaid

Reading through the code, I've found out that KC is matching the users' name by lower-casing the DisplayName.
But Twitch allows users to set DisplayName to non-alphabet characters like Kanji (Japanese/Chinese characters) and Hankul (Korian characters).

When you open your Twitch Settings page (https://www.twitch.tv/settings/profile),
1. If your language settings is Alphabet based, your DisplayName can only customize capitalization.
2. If you change the language settings to e.g. Japanese, your DisplayName can be customized to Japanese/Korean/Chinese characters.

You don't have to live in these countries! You just need to change the language settings from Twitch upper-right menu.

So users can have ChannelName `test` and set DisplayName `テスト` ("test" written in Japanese).

In these cases, commands like `OnCommand b 10 !example` doesn't work because lower-cased DisplayName doesn't match ChannelName so `テスト` is not recognized as a broadcaster.

I've tested and `OnCommand u テスト 10 !example` works in this case.

We need a way to distinguish DisplayName and ChannelName in the code to actually fix this issue.

**Comment by Kruiser8** [comment]
Hey there,

Thanks for pointing out this issue! I fixed the issue in develop and it will be included in the next update. If interested, you can check it out here: https://github.com/Kruiser8/Kruiz-Control/tree/develop

-Kruiser

**Comment by formulynx** [comment]
Hi @Kruiser8 , thank you very much for the quick fix!
I've checked the develop branch code and looks great.
I'm looking forward to the next update!
