### ISSUE TITLE
TTS audio can't be controlled through obs

### ISSUE THREAD

**Issue by woodman-exe** [Kruiser8/Kruiz-Control#48]
The new tts method forces output through desktop audio, even when using the Control Audio via OBS option.

![image_2022-08-11_151127842](https://user-images.githubusercontent.com/111037280/184068289-d9121a76-72a5-4c09-9e25-429712ef1271.png)

![image_2022-08-11_151057219](https://user-images.githubusercontent.com/111037280/184068246-d630de8e-f9a3-42ba-add4-5fdaa287e00e.png)

**Comment by woodman-exe** [comment]
I found a workaround by changing the app device preference in OBS, which works for now.
![image](https://user-images.githubusercontent.com/111037280/184073525-1c3c1447-9459-49e6-9582-eee7e962aebc.png)

**Comment by Kruiser8** [comment]
TTS is played through the desktop audio. This is intended. It's unfortunate for this use case, but intended.

Glad you found a workaround.
