### ISSUE TITLE
OBS Source can no longer be used to change the visibility of sources that are in a group/folder in v1.6.0

### ISSUE THREAD

**Issue by ReizenKaito** [Kruiser8/Kruiz-Control#55]
Hello! As of Kruiz Control v1.6.0, we are unable to change the visibility of sources in a group/folder. I realized this is working as intended, as it is noted in the notes section of that release. However, this can be very difficult for those of us who have multiple sources that we need controlled. This results in multiple entries and bloats up the sources panel in OBS.

Is there any particular reason why this feature has this limitation? Is there any possibility of it returning? Thank you so much!

**Comment by Kruiser8** [comment]
In the meantime, you _can_ use [`OBS SceneSource`](https://github.com/Kruiser8/Kruiz-Control/blob/master/js/Documentation.md#obs-scenesource) to update sources within a group. However, you have to put the group name as the scene.

> Is there any particular reason why this feature has this limitation?
The OBS websocket used to support changing the visibility of a source, regardless of if it was in a group or not. They removed the call in the recent update.

> Is there any possibility of it returning?
Yes, we're determining the best way to replace the functionality.

-Kruiser

**Comment by Kruiser8** [comment]
v1.6.1 resolves this issue.
