### ISSUE TITLE
How to call API and send response to Chat

### ISSUE THREAD

**Issue by Epyxx** [Kruiser8/Kruiz-Control#59]
Hey there,
i want to call an API url and send the response text to the chat i tried the following but it did not work:

> OnCommand bm 0 !next
> API GET http://localhost/api.php?action=next
> Chat Send "{api_data}"

and

> OnCommand bm 0 !next
> API GET http://localhost/api.php?action=next
> Chat Send "{response}"

what is the correct way to do this?

Thanks!

**Comment by Kruiser8** [comment]
Hey Epyxx,

The first option you send is correct. API response data is available as the `api_data` parameter. Did you get any value sent to chat like `Error`?

Something to note, OBS 27+ updated the browser source and any locally hosted APIs will need to include an `Access-Control-Allow-Origin` header value to allow OBS to call them.

```php
<?php
header("Access-Control-Allow-Origin: *");
```

Thanks,
Kruiser

**Comment by Epyxx** [comment]
Thanks! The header was the problem :) Before i got no response at all, there were no message sent to chat.
But now with the header it works! :D
