### ISSUE TITLE
Multiple users for command

### ISSUE THREAD

**Issue by Epyxx** [Kruiser8/Kruiz-Control#61]
Hi there,

i want a command to be used by multiple users. is there a way to put multiple usernames instead of only one?
currently i have copied that action for every user but that fills the triggers.txt very much. maybe something like this:

    OnCommand u [user1,user2,user3,user4] 0 !command

And then i want the same thing in the opposite way, like a command for everyone except a few users, like so:

    OnCommand e 0 !command
    If {user} in [user1,user2,user3,user4]
    Chat Send "You have no permission for this command"
    Else
    Chat Send "Cool Command"

Is something possible with Kruiz?

Thanks!

**Comment by Kruiser8** [comment]
Hey Epyxx,

You could use a list?
```m
OnInit
List Add CommandUserList user1
List Add CommandUserList user1
List Add CommandUserList user1

**Comment by Kruiser8** [comment]
Support for `OnCommand u user1,user2,user3,user4 0 !command` added in the upcoming release.
