### ISSUE TITLE
Shoutout doesn't work

### ISSUE THREAD

**Issue by Epyxx** [Kruiser8/Kruiz-Control#62]
Hi there,
i have created an OnSETwitchRaid event with a message and shoutout command, but the shoutout does not work! The streamelements connection works fine.

    OnSETwitchRaid
    Chat Send "/shoutout {user}"
    Chat Send "{user} just raided the channel with {raiders} viewers PogChamp"

The second message appears in chat but the shoutout is not executed.

**Comment by Kruiser8** [comment]
The `/shoutout` command does not work with Kruiz Control. This is a known limitation.

**Comment by alkaris2** [comment]
How about a `OnChatCommand` followed by a `Chat Send` that should still work, since you're not executing the chat command itself, but checking for a chat command being used.
