### ISSUE TITLE
random tts

### ISSUE THREAD

**Issue by Ghitim** [Kruiser8/Kruiz-Control#66]
i'm trying to have an onspeak of a specific user trigger a random tts speech line which 95% works, however, the voice variable is ignored and the default voice is used, additionally you cannot use the wait/nowait option as it will read that as part of the tts as well

random "TTS 'Microsoft James - English (Australia)' - - - [line1]" "TTS 'Microsoft James - English (Australia)' - - - [line2]" "TTS 'Microsoft James - English (Australia)' - - - [line3]"

**Comment by Kruiser8** [comment]
Hey @Ghitim,

It looks like the TTS actions are missing one input. There should be four before the text: volume, pitch, rate, and wait/nowait. I can confirm that the below works, uses the provided voice, and waits before playing the music.
```m 
OnInit
Random "TTS 'Microsoft Zira - English (United States)' - - - wait [line1]" "TTS 'Microsoft Mark - English (United States)' - - - wait [line2]" "TTS 'Microsoft Sabina - Spanish (Mexico)' - - - wait [line3]"
Play 30 no "MashiahMusic__Kygo-Style-Melody.wav"
```

-Kruiser

**Comment by Ghitim** [comment]
when i keep the wait in it reads wait at the start of the tts

**Comment by Ghitim** [comment]
i see what i've done. there's an "it's" in the text i'm trying to say and appears to be no way to escape the ' so it's extra and breaks the cmd structure.
Thanks! :D
