### ISSUE TITLE
Kruiz-Control on other computer

### ISSUE THREAD

**Issue by Zykino** [Kruiser8/Kruiz-Control#7]
I'm trying to replicate some kind of streamdeck but with Open Source software, a Raspberry PI with its official screen and a case.

 So I came across your project that seems really fiting to add to my "raspi-deck". You have a great documentation and even some videos (that may be too much to create a video for each minor/patch release but if you like to do so ^^).

Since I want my raspi to hold everything related to automate my stream, I wanted to install Kruiz-Control on it. I have 2 questions related to that:

1. If I want to add the source from my PI in my OBS on my streaming PC, do I need nginx or something like that so OBS can access the file?
2. Wouldn't Kruiz-Control work exactly the same if it is open from the browser on my Raspberry PI? (I'm already having the browser opened with https://github.com/t2t2/obs-tablet-remote on full screen, so a background tab won't annoy me).

Thank you for this project (and Mrgregles for the discovery).

**Comment by Kruiser8** [comment]
Hi Zykino, appreciate you reaching out. I'm trying to do videos for each release (monthly) just to make sure I cover what's new. This next update is dangerously large so a video may be necessary.

I cannot assist with Raspberry PI specific things since I don't have experience there but I can say that:
- Kruiz Control doesn't work in browsers outside of OBS or SLOBS. 
- You'd have to update the OBS/SLOBS settings to use the correct IPs.
- MrGoodBytes (if you know him) got KC running locally by throwing it in a virtual host and running under apache. If you want to "serve" KC from your raspi-deck, then OBS will have to have an address to access the file.

-Kruiser

**Comment by Zykino** [comment]
> You'd have to update the OBS/SLOBS settings to use the correct IPs.
It is the other way around, instead of setting `localhost:4444` I need to set `192.168.X.Y:4444`.

I tried using KC on Firefox and it cannot read the local files so cannot be configured. Maybe with a reverse proxy this will work.

I don’t know him but yeah I need a reverse proxy. Nothing is Specific to the Raspberry PI.
Maybe you can add a sentence in the doc:
```
# Installation
<Let  as is, maybe add a sentence telling to follow either the Local or the Remote depending on if Kruiz-Control and OBS are on the same machine or not>
## Add as a Local Browser Source
<Let  as is>
### Steps for adding to OBS/SLOBS
<Let  as is>

## Add as a Remote Browser Source
<Same as for Local Browser Source>

### Make Kruiz-Control accessible on remote
You will need to have a reverse proxy installed on the computer hosting Kruiz-Control to serve the **index.html** file. You can configure `nginx` or `apache` for example. <I will try to use nginx and will give you my configuration if you want to add examples>.
Opening the file in an other browser than OBS will not work.

### Steps for adding to OBS/SLOBS
* In OBS, under Sources click the + icon to add a new Browser source.
* Name it and select OK.
* Set the URL to point to the `index.html` file on the other machine. If the machine have the IP `192.168.0.1`, then the source may be `192.168.0.1/Kruiz-Control/index.html`.
* Recommended to set the width/height to 100 or less to reduce the size of the source. <Does that really change something ? Less memory used or something ?>
```

**Comment by Kruiser8** [comment]
Hi Zykino,
> It is the other way around...

When I said "update the OBS/SLOBS settings", I meant update the Kruiz Control settings files for OBS/SLOBS. I believe that's what you're thinking as well.
> I tried using KC on Firefox and it cannot read the local files so cannot be configured.

Correct, KC does not work completely in any browser. It half works in Microsoft Edge.
> ...maybe add a sentence depending on if [KC] and OBS are on the same machine or not

The expectation is that KC is on the same computer and running in OBS/SLOBS, so I'll add a note that emphasizes that.
> Does that really change something ? Less memory used or something ?

I'm unsure if changing the size actually affects it but I figure it's less layer calculation that OBS/SLOBS needs to calculate. It's safer than sorry, I assume.
-Kruiser

**Comment by richard4339** [comment]
I can confirm is is usable over Apache/nginx/etc. Even if on the same box, localhost is not permissable in the obs websocket. If you go that route, the nice thing is that console.log() is easily viewable.

And since Windows is now automatically upgrading this via Windows Update, I'll point out that the new Chromium based Microsoft Edge has the cross-site origin blocks in place...

**Comment by Zykino** [comment]
Well thanks both of you, I made it works by installing `nginx`. In the file `/etc/nginx/sites-available/kruiz-control` I have the configuration below (I am not an nginx expert), and I have a symbolic link to this file in the folder `/etc/nginx/sites-enabled/` (Thoses are Linux path but they are the standard folders to configure `nginx`).
```
server {
	listen 8282;
	listen [::]:8282;

	root /home/pi/Documents/Code; # Path to Kruiz-Control directory (where I git clonned it)
	index index.html;

	location /Kruiz-Control/ {
	}
}
```
Then on any computer at my house I can just open a tab to `http://<raspberry-pi-IP-or-hostname>:8282/Kruiz-Control/`. Which mean I should be able to just open it as a browser source as you recommend. Or not and in that case I should be sure to only have it opened once. (otherwise when I send a command I have two responses).

**Comment by Kruiser8** [comment]
Marking as closed since you found a solution.
