### ISSUE TITLE
Invalid Password of Permission Scopes Error

### ISSUE THREAD

**Issue by alkaris2** [Kruiser8/Kruiz-Control#71]
This appears to be a bug because I've set valid password and permission scopes, but when I use a channel redeem on Twitch it doesn't work when it should. It was working previously, never changed anything, but then suddenly it decides it doesn't want to work because it claims invalid password or permissions scope. I tried changing to a new OAuth Token to see if that fixed the issue, but the issue remains, but like I said nothing WAS changed, it's been fine until now. Perhaps it's a change on Twitch side that broke the API that Kruiz-Control interacts with.

```
14:43:51.367: [obs-browser: 'Kruiz_Control'] Error: Kruiz Control v1.6.2 Initialized (http://absolute//home/alkaris/Kruiz-Control/js/index.js:4)
14:43:51.382: [obs-websocket] [WebSocketServer::onOpen] New WebSocket client has connected from [::ffff:127.0.0.1]:47852
14:43:51.389: [obs-websocket] [WebSocketServer::onClose] WebSocket client `[::ffff:127.0.0.1]:47852` has disconnected with code `4009` and reason: Authentication failed.
14:43:51.392: [obs-browser: 'Kruiz_Control'] Error: {"code":4009} (http://absolute//home/alkaris/Kruiz-Control/js/obs/obs-wrapper.js:22)
14:43:52.097: [obs-browser: 'Kruiz_Control'] Error: Invalid Password or Permission Scopes (channel:read:redemptions, user:read:email) (https://cdn.jsdelivr.net/npm/comfy.js@latest/dist/comfy.min.js:1)
14:43:55.764: [obs-browser: 'Kruiz_Control'] Error: Kruiz Control: Too many inputs provided for API.
14:43:55.764: Expected (2 inputs): ["action","url"]
```

It has valid password set, and has valid permission scopes set, but as the above error shows it seems to think otherwise.

**Comment by Kruiser8** [comment]
Hi @alkaris2,

The `Invalid Password or Permission Scopes` error is unrelated to channel point redeems. Channel point redeems in v1.6.2 are based on your `settings/twitch/user.txt` file. No oauth code/scope is required.

Double check your [Twitch user setting](https://github.com/Kruiser8/Kruiz-Control/blob/v1.6.2/settings/Settings.md#usertxt-1) is set to the right channel and then also validate that the channel point reward name matches exactly (including any extra spaces).

If it still doesn't work, please provide the event that you're trying to run as well as a link to your twitch channel.

Thanks,
Kruiser

**Comment by Kruiser8** [comment]
Hi @alkaris2,

I'm going to close this ticket. Please follow up if you have any questions.

Thanks,
Kruiser

**Comment by StarveTheEgo** [comment]
Hello sir, i am having the same error message
```
Invalid Password or Permission Scopes (channel:read:redemptions, user:read:email)
```

I am a developer of things myself, so before going here, i quadruple-dozens-of-times checked everything related to settings and re-created twitch Application three times just to be sure, re-done the entire thing from scratch multiple times, and i still have this error, i spent 5 hours on it and still cannot bear with this error

What else i can miss? I completely follow the installation+settings guides

**Comment by StarveTheEgo** [comment]
Nevermind i randomly added these additional permissions (especially chat read/write ones) and it works for me now:
`chat:read
chat:edit
channel:manage:raids
channel:read:vips
user:bot
user:read:chat
user:write:chat
user:read:emotes`
