### ISSUE TITLE
Suggestion: Ad Break Trigger

### ISSUE THREAD

**Issue by TheTaraStark** [Kruiser8/Kruiz-Control#76]
New trigger for when midroll ads begin. Twitch added it to their API in October and it's out of beta. [Documentation here](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelad_breakbegin)

`OnTWAdBreak` Could be used to trigger chat messages (prompts to subscribe, get prime, thank viewers for supporting with ads, etc), make countdown timers visible on stream to show how far stream is into ad break, etc

`<duration>` would probably be the most useful parameter here (change chat messages or trigger different timers), though `<is_automatic>` could also be neat for conditional "Streamer is taking a break now so you don't miss the action!" or "Streamer had no control, ads have to run sometime" messages, etc

**Comment by TheTaraStark** [comment]
Just discovered "Get Ad Schedule" was added to Twitch's API at some point. [https://dev.twitch.tv/docs/api/reference/#get-ad-schedule](https://dev.twitch.tv/docs/api/reference/#get-ad-schedule)

These could be strung together to trigger actions _before_ ads run. I'm envisioning situations where a warning allows viewers to beg for a snooze, where viewers choose to sub before ads hit, etc.

**Comment by alkaris2** [comment]
I think this would a great feature to implement, I think to make this work you could parse the output into JSON format from the Get Ad Schedule, and it'll be this file that gets updated when it the event is triggered which will update on the overlays and/or display a notification on chat or on screen.

```JSON
{
  "OnTwAdBreak": {
  "AdSchedule": "2023-08-01T23:08:18+00:00",
  "AdMsg": [
    {
    "message": "",
    },
  ],
  "AdDuration": "<n seconds>",
    "data": [
    {
      "next_ad_at" : "2023-08-01T23:08:18+00:00",
      "last_ad_at" : "2023-08-01T23:08:18+00:00",
      "duration" : "60",
      "preroll_free_time" : "90",
      "snooze_count" : 1,
      "snooze_refresh_at" : "2023-08-01T23:08:18+00:00",
    },
  ],
  "CommandExec":"OnTWAdBreak $AdMsg"
  },
}

**Comment by Kruiser8** [comment]
Added in the lastest release, v2.0.5.
