### ISSUE TITLE
Suggestion: Here Documents

### ISSUE THREAD

**Issue by Altazimuth** [Kruiser8/Kruiz-Control#79]
Some way of specifying multiline strings. Would be extremely useful for `Function` and similar. An example would be `'''` in Python.

The part I'm unclear on is how this would interact with relative line jumps.

**Comment by Kruiser8** [comment]
This is added in v2.0.6.
> When skipping lines, multi-line inputs are considered one line and comments are not considered.

**Comment by Altazimuth** [comment]
Thanks so much!
