### ISSUE TITLE
Add trigger OnOBSSwitchSource

### ISSUE THREAD

**Issue by Zykino** [Kruiser8/Kruiz-Control#8]
Put the name you want, the idea is to toggle a source from outside of Kruiz-Control (to show a video), but let Kruiz-Control to react to this and hide the source after a delay, or do any action

I think you can use https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sceneitemvisibilitychanged for that (but I’m not familiar with OBS-ws code).

**Comment by Kruiser8** [comment]
This will be released in the next version (end of June).
